### ISSUE TITLE
Buggy spritesheet algorithm

### ISSUE THREAD

**Issue by agnither** [DragonBones/DesignPanel#16]
When I trying to set x2 export scale for the 2048x2048 texture, it crashes with exception (Error #2015: Invalid BitmapData), but it can't be more than 4096x4096 even if 2048x2048 spritesheet packed up to the limit.

**Comment by agnither** [comment]
When I exported with 1.5 scale, I got 4096x2048 spritesheet.
Scale 1.6 - same error.
Seems like you have a logical mistake in algorithm.

**Comment by akdcl** [comment]
Thank you, the bug has been fixed in dev branch

**Comment by agnither** [comment]
Thanks for fast fix!
Could you please build zxp from master branch within this fix?
Because master branch have a possibility to export float scale textures, but dev still doesn't.

**Comment by agnither** [comment]
BTW, the problem was solved indeed
